
export const cakes2 = [
  {
    id: 393,
    name: "Bundt Cake",
    description:
      "Delight in the classic Bundt Cake, known for its unique ring shape, moist texture, and various flavors like lemon, vanilla, or marbled chocolate.",
    image:
      "https://imgs.search.brave.com/baiSsWy4_PlQ56OL53UkCIv5-U6iyR-AUt6vgrWiQ70/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy9idW5k/dC1jYWtlLXJlY2lw/ZXMtZ3Vpbm5lc3Mt/Y2FrZS02NGRmY2Mw/NGM3ZTBhLmpwZWc_/Y3JvcD0xeHc6MXho/O2NlbnRlcix0b3Am/cmVzaXplPTk4MDoq",
    price: 16.99,
    size: "10-inch bundt",
    availability: true,
    averageRating: 4.7,
    reviews: [
      {
        username: "BundtCakeFanatic",
        comment: "Moist and flavorful! Love the different flavor options.",
        rating: 4.9,
      },
      {
        username: "CakeLover2023",
        comment: "Classic and delicious. Perfect for any celebration!",
        rating: 4.5,
      },
    ],
    nutritionFacts: {
      calories: 280,
      totalFat: "16g",
      carbohydrates: "32g",
      protein: "4g",
    },
    ingredients: [
      { name: "Butter", quantity: "200g" },
      { name: "Sugar", quantity: "220g" },
      { name: "Eggs", quantity: "4 large" },
      { name: "Flour", quantity: "250g" },
      { name: "Baking powder", quantity: "1 1/2 tsp" },
      { name: "Flavor extract (lemon/vanilla)", quantity: "2 tsp" },
    ],
    tags: ["bundt cake", "moist", "ring-shaped", "classic", "various flavors"],
    searchTags: [
      "bundt cake",
      "10-inch bundt",
      "moist cake",
      "celebration dessert",
    ],
    allergens: ["eggs", "dairy"],
    ageGroups: ["adults", "teens"],
    relations: ["family", "friends"],
    isVegetarian: true,
    featured: true,
    category: "Butter Cakes",
  },
  {
    id: 394,
    name: "Butter Pound Cake",
    description:
      "Indulge in the richness of a classic Butter Pound Cake, boasting a dense and buttery texture, perfect for various toppings or enjoying on its own.",
    image:
      "https://imgs.search.brave.com/ZxHTSqdCDlrsCgLYhTXFVp2RoIg1Nn3mSNG2Sqm0-9w/rs:fit:500:0:0/g:ce/aHR0cHM6Ly93d3cu/dGFzdGVvZmhvbWUu/Y29tL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDE4LzA3L0J1dHRl/ci1Qb3VuZC1DYWtl/X0VYUFNfSENBMThf/MzcxMjVfRDAyXzIz/XzNiLTMuanBnP2Zp/dD03MDAsMTAyNA",
    price: 17.99,
    size: "10-inch loaf",
    availability: true,
    averageRating: 4.8,
    reviews: [
      {
        username: "PoundCakeExpert",
        comment:
          "Rich and delightful! A classic treat with a wonderful texture.",
        rating: 4.9,
      },
      {
        username: "CakeConnoisseur2023",
        comment:
          "Wonderfully buttery and satisfying. Perfect with a cup of coffee.",
        rating: 4.7,
      },
    ],
    nutritionFacts: {
      calories: 300,
      totalFat: "20g",
      carbohydrates: "35g",
      protein: "4g",
    },
    ingredients: [
      { name: "Butter", quantity: "300g" },
      { name: "Sugar", quantity: "250g" },
      { name: "Eggs", quantity: "5 large" },
      { name: "Flour", quantity: "300g" },
      { name: "Vanilla extract", quantity: "2 tsp" },
      { name: "Baking powder", quantity: "1 tsp" },
    ],
    tags: ["butter pound cake", "dense", "buttery", "classic", "loaf cake"],
    searchTags: [
      "butter pound cake",
      "10-inch loaf",
      "buttery cake",
      "classic dessert",
    ],
    allergens: ["eggs", "dairy"],
    ageGroups: ["adults", "seniors"],
    relations: ["family", "friends"],
    isVegetarian: true,
    featured: true,
    category: "Butter Cakes",
  },
  {
    id: 395,
    name: "Butter Sponge Cake",
    description:
      "Savor the delicate and moist Butter Sponge Cake, boasting a light and airy texture enriched with a buttery flavor, perfect for various fillings or enjoying on its own.",
    image:
      "https://imgs.search.brave.com/JccNWk7JFl2EGRe6JrVavbeB_YL7naIb_u3L-UbvbaE/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9jYWtl/c2J5bWsuY29tL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDIzLzAz/L1RlbXBsYXRlLVNp/emUtZm9yLUJsb2ct/UGhvdG9zLTI4LTgw/MngxMDI0LmpwZw",
    price: 14.99,
    size: "9-inch round",
    availability: true,
    averageRating: 4.6,
    reviews: [
      {
        username: "SpongeCakeLover",
        comment: "Light and delightful! The buttery taste is perfect.",
        rating: 4.8,
      },
      {
        username: "CakeEnthusiast2023",
        comment: "Moist and flavorful - a classic cake for any occasion.",
        rating: 4.5,
      },
    ],
    nutritionFacts: {
      calories: 240,
      totalFat: "14g",
      carbohydrates: "30g",
      protein: "3g",
    },
    ingredients: [
      { name: "Butter", quantity: "200g" },
      { name: "Sugar", quantity: "180g" },
      { name: "Eggs", quantity: "4 large" },
      { name: "Flour", quantity: "220g" },
      { name: "Baking powder", quantity: "1 1/2 tsp" },
      { name: "Milk", quantity: "100ml" },
    ],
    tags: ["butter sponge cake", "moist", "buttery", "light", "round cake"],
    searchTags: [
      "butter sponge cake",
      "9-inch round",
      "moist cake",
      "classic dessert",
    ],
    allergens: ["eggs", "dairy"],
    ageGroups: ["adults", "teens"],
    relations: ["family", "friends"],
    isVegetarian: true,
    featured: true,
    category: "Butter Cakes",
  },
  {
    id: 396,
    name: "Butter Rum Cake",
    description:
      "Enjoy the rich and flavorful Butter Rum Cake, featuring a buttery taste infused with a hint of rum, perfect for indulging in a delightful dessert.",
    image:
      "https://imgs.search.brave.com/guiiLSOo7Kt53xJ6PuaMv9m_5fZS0E_SnA5fMi1hMNI/rs:fit:500:0:0/g:ce/aHR0cHM6Ly93d3cu/dGhla2l0Y2hlbm1h/Z3BpZS5jb20vd3At/Y29udGVudC91cGxv/YWRzL2ltYWdlcy8y/MDA5LzA5L1BlY2Fu/QnV0dGVyUnVtQ2Fr/ZTQtNzAweDQ2Ny5q/cGc",
    price: 18.99,
    size: "8-inch round",
    availability: true,
    averageRating: 4.7,
    reviews: [
      {
        username: "RumCakeFanatic",
        comment: "Rich and delicious! The rum flavor is just perfect.",
        rating: 4.8,
      },
      {
        username: "CakeLover2023",
        comment: "Moist and flavorful - a great treat for any celebration.",
        rating: 4.6,
      },
    ],
    nutritionFacts: {
      calories: 260,
      totalFat: "15g",
      carbohydrates: "30g",
      protein: "3g",
    },
    ingredients: [
      { name: "Butter", quantity: "200g" },
      { name: "Sugar", quantity: "180g" },
      { name: "Rum extract", quantity: "2 tbsp" },
      { name: "Eggs", quantity: "4 large" },
      { name: "Flour", quantity: "220g" },
      { name: "Baking powder", quantity: "1 1/2 tsp" },
    ],
    tags: [
      "butter rum cake",
      "flavorful",
      "buttery",
      "round cake",
      "rum-infused",
    ],
    searchTags: [
      "butter rum cake",
      "8-inch round",
      "flavorful cake",
      "celebration dessert",
    ],
    allergens: ["eggs", "dairy"],
    ageGroups: ["adults", "seniors"],
    relations: ["family", "friends"],
    isVegetarian: true,
    featured: true,
    category: "Butter Cakes",
  },
  {
    id: 397,
    name: "Butter Almond Cake",
    description:
      "Experience the delightful and nutty Butter Almond Cake, blending a buttery taste with the richness of almond, perfect for a flavorful dessert indulgence.",
    image:
      "https://imgs.search.brave.com/KlYP4ljox8-VaU8WKJhJahetemkR5hA1CSFbE9p1zZM/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMwMS5ueXQuY29t/L2ltYWdlcy8yMDE1/LzEwLzE1L2Rpbmlu/Zy8xNUNPT0tJTkct/QlVUVEVSQ0FLRTIv/MTVDT09LSU5HLUJV/VFRFUkNBS0UyLWFy/dGljbGVMYXJnZS12/Mi5qcGc_dz0xMjgw/JnE9NzU",
    price: 16.99,
    size: "9-inch round",
    availability: true,
    averageRating: 4.6,
    reviews: [
      {
        username: "AlmondCakeLover",
        comment: "Delightful and nutty! The almond flavor is perfect.",
        rating: 4.7,
      },
      {
        username: "CakeConnoisseur2023",
        comment: "Rich and flavorful - a great cake for any occasion.",
        rating: 4.5,
      },
    ],
    nutritionFacts: {
      calories: 250,
      totalFat: "16g",
      carbohydrates: "28g",
      protein: "3g",
    },
    ingredients: [
      { name: "Butter", quantity: "180g" },
      { name: "Sugar", quantity: "200g" },
      { name: "Almond extract", quantity: "2 tsp" },
      { name: "Eggs", quantity: "3 large" },
      { name: "Flour", quantity: "230g" },
      { name: "Baking powder", quantity: "1 tsp" },
    ],
    tags: [
      "butter almond cake",
      "nutty",
      "buttery",
      "round cake",
      "almond-infused",
    ],
    searchTags: [
      "butter almond cake",
      "9-inch round",
      "nutty cake",
      "flavorful dessert",
    ],
    allergens: ["eggs", "dairy", "nuts"],
    ageGroups: ["adults", "teens"],
    relations: ["family", "friends"],
    isVegetarian: true,
    featured: true,
    category: "Butter Cakes",
  },
  {
    id: 398,
    name: "Classic Chiffon Cake",
    description:
      "Indulge in the light and airy Classic Chiffon Cake, known for its soft texture and delightful taste, perfect for any occasion.",
    image:
      "https://imgs.search.brave.com/GtzzWViALIbQIv6_qu3xDtpTcEnIYsHPsQriLupDZ5I/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMwMS5ueXQuY29t/L2ltYWdlcy8yMDIy/LzEyLzA0L2Rpbmlu/Zy8wNEVBVC1jaGlm/Zm9uLWNha2UvMDRF/QVQtY2hpZmZvbi1j/YWtlLWFydGljbGVM/YXJnZS5qcGc_dz0x/MjgwJnE9NzU",
    price: 14.99,
    size: "10-inch round",
    availability: true,
    averageRating: 4.7,
    reviews: [
      {
        username: "ChiffonCakeFanatic",
        comment: "Light and delightful! The texture is amazing.",
        rating: 4.8,
      },
      {
        username: "CakeLover2023",
        comment: "Moist and flavorful - a classic cake for any celebration.",
        rating: 4.6,
      },
    ],
    nutritionFacts: {
      calories: 200,
      totalFat: "8g",
      carbohydrates: "30g",
      protein: "3g",
    },
    ingredients: [
      { name: "Cake flour", quantity: "200g" },
      { name: "Sugar", quantity: "180g" },
      { name: "Eggs", quantity: "6 large" },
      { name: "Vegetable oil", quantity: "100ml" },
      { name: "Baking powder", quantity: "1 1/2 tsp" },
      { name: "Vanilla extract", quantity: "2 tsp" },
    ],
    tags: [
      "classic chiffon cake",
      "light",
      "airy",
      "round cake",
      "soft texture",
    ],
    searchTags: [
      "classic chiffon cake",
      "10-inch round",
      "light cake",
      "celebration dessert",
    ],
    allergens: ["eggs"],
    ageGroups: ["adults", "teens"],
    relations: ["family", "friends"],
    isVegetarian: true,
    featured: true,
    category: "Chiffon Cakes",
  },
  {
    id: 399,
    name: "Lemon Chiffon Cake",
    description:
      "Savor the zesty and light Lemon Chiffon Cake, boasting a delightful lemon flavor and a soft, airy texture, perfect for a refreshing dessert.",
    image:
      "https://imgs.search.brave.com/zIiavD6LjILvk27_GDVh2-dcdV94wHA5UOBW7Jiid6w/rs:fit:500:0:0/g:ce/aHR0cHM6Ly93d3cu/dGFzdGVvZmhvbWUu/Y29tL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDE3LzA5L2V4cHM0/MDE1Ml9DVzE2MzY4/MUQxMl8wOV8yYi5q/cGc",
    price: 16.99,
    size: "9-inch round",
    availability: true,
    averageRating: 4.9,
    reviews: [
      {
        username: "LemonCakeLover",
        comment: "Zesty and delicious! The lemon flavor is just perfect.",
        rating: 5,
      },
      {
        username: "CakeConnoisseur2023",
        comment: "Moist and flavorful - a perfect cake for a refreshing treat.",
        rating: 4.8,
      },
    ],
    nutritionFacts: {
      calories: 220,
      totalFat: "9g",
      carbohydrates: "32g",
      protein: "3g",
    },
    ingredients: [
      { name: "Cake flour", quantity: "180g" },
      { name: "Sugar", quantity: "160g" },
      { name: "Eggs", quantity: "5 large" },
      { name: "Vegetable oil", quantity: "120ml" },
      { name: "Baking powder", quantity: "1 1/2 tsp" },
      { name: "Lemon zest and juice", quantity: "3 lemons" },
    ],
    tags: [
      "lemon chiffon cake",
      "zesty",
      "airy",
      "round cake",
      "refreshing dessert",
    ],
    searchTags: [
      "lemon chiffon cake",
      "9-inch round",
      "zesty cake",
      "refreshing dessert",
    ],
    allergens: ["eggs"],
    ageGroups: ["adults", "teens"],
    relations: ["family", "friends"],
    isVegetarian: true,
    featured: true,
    category: "Chiffon Cakes",
  },
  {
    id: 400,
    name: "Orange Chiffon Cake",
    description:
      "Indulge in the citrusy delight of Orange Chiffon Cake, featuring a light and fluffy texture with the refreshing essence of oranges, a perfect treat for citrus lovers.",
    image:
      "https://imgs.search.brave.com/A2kBWzgdaxkxhET7F0aZ9fYO0rHClWEAxCFB-E8hFqg/rs:fit:500:0:0/g:ce/aHR0cHM6Ly93d3cu/c291dGhlcm5saXZp/bmcuY29tL3RobWIv/V1JKRExaejFncWJ4/Y2dyMG50ZGlFc1B4/bU9JPS8xNTAweDAv/ZmlsdGVyczpub191/cHNjYWxlKCk6bWF4/X2J5dGVzKDE1MDAw/MCk6c3RyaXBfaWNj/KCkvU291dGhlcm4t/TGl2aW5nLU9yYW5n/ZV9jaGlmZm9uX2Nh/a2VfM3g0XzAwMi0w/NjU3NTQwNjNhMjg0/MDhiOWFjNjQ4ZTg3/MDA4ZTNhNS5qcGc",
    price: 15.99,
    size: "8-inch round",
    availability: true,
    averageRating: 4.8,
    reviews: [
      {
        username: "CitrusCakeFanatic",
        comment: "Light and delightful! The orange flavor is amazing.",
        rating: 4.9,
      },
      {
        username: "CakeConnoisseur2023",
        comment: "Moist and flavorful - a refreshing cake for any occasion.",
        rating: 4.7,
      },
    ],
    nutritionFacts: {
      calories: 210,
      totalFat: "8g",
      carbohydrates: "30g",
      protein: "3g",
    },
    ingredients: [
      { name: "Cake flour", quantity: "190g" },
      { name: "Sugar", quantity: "170g" },
      { name: "Eggs", quantity: "4 large" },
      { name: "Vegetable oil", quantity: "110ml" },
      { name: "Baking powder", quantity: "1 1/2 tsp" },
      { name: "Orange zest and juice", quantity: "3 oranges" },
    ],
    tags: [
      "orange chiffon cake",
      "citrusy",
      "fluffy",
      "round cake",
      "refreshing dessert",
    ],
    searchTags: [
      "orange chiffon cake",
      "8-inch round",
      "citrusy cake",
      "refreshing dessert",
    ],
    allergens: ["eggs"],
    ageGroups: ["adults", "teens"],
    relations: ["family", "friends"],
    isVegetarian: true,
    featured: true,
    category: "Chiffon Cakes",
  },
  {
    id: 401,
    name: "Orange Chiffon Cake",
    description:
      "Indulge in the citrusy delight of Orange Chiffon Cake, featuring a light and fluffy texture with the refreshing essence of oranges, a perfect treat for citrus lovers.",
    image:
      "https://imgs.search.brave.com/zBKLuvISCrLeyCgQKJD2_6bYYTtFELuvxjb27TktMm4/rs:fit:500:0:0/g:ce/aHR0cHM6Ly93d3cu/dGFzdGluZ3RhYmxl/LmNvbS9pbWcvZ2Fs/bGVyeS9vcmFuZ2Ut/Y2hpZmZvbi1jYWtl/LXJlY2lwZS9pbnRy/by0xNjM5MDg0NTY3/LmpwZw",
    price: 15.99,
    size: "8-inch round",
    availability: true,
    averageRating: 4.8,
    reviews: [
      {
        username: "CitrusCakeFanatic",
        comment: "Light and delightful! The orange flavor is amazing.",
        rating: 4.9,
      },
      {
        username: "CakeConnoisseur2023",
        comment: "Moist and flavorful - a refreshing cake for any occasion.",
        rating: 4.7,
      },
    ],
    nutritionFacts: {
      calories: 210,
      totalFat: "8g",
      carbohydrates: "30g",
      protein: "3g",
    },
    ingredients: [
      { name: "Cake flour", quantity: "190g" },
      { name: "Sugar", quantity: "170g" },
      { name: "Eggs", quantity: "4 large" },
      { name: "Vegetable oil", quantity: "110ml" },
      { name: "Baking powder", quantity: "1 1/2 tsp" },
      { name: "Orange zest and juice", quantity: "3 oranges" },
    ],
    tags: [
      "orange chiffon cake",
      "citrusy",
      "fluffy",
      "round cake",
      "refreshing dessert",
    ],
    searchTags: [
      "orange chiffon cake",
      "8-inch round",
      "citrusy cake",
      "refreshing dessert",
    ],
    allergens: ["eggs"],
    ageGroups: ["adults", "teens"],
    relations: ["family", "friends"],
    isVegetarian: true,
    featured: true,
    category: "Chiffon Cakes",
  },
];

