export const THEME_CHANGE = "THEME_CHANGE";


export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";


export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";


export const GET_USER_REQUEST="GET_USER_REQUEST";
export const GET_USER_SUCCESS="GET_USER_SUCCESS";
export const GET_USER_FAILURE="GET_USER_FAILURE";

export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";


export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE";

export const FETCH_FULL_CART_DATA_SUCCESS = "FETCH_FULL_CART_DATA_SUCCESS";

export const FETCH_PRODUCT_QUANTITY_REQUEST = "FETCH_PRODUCT_QUANTITY_REQUEST";
export const FETCH_PRODUCT_QUANTITY_SUCCESS = "FETCH_PRODUCT_QUANTITY_SUCCESS";
export const FETCH_PRODUCT_QUANTITY_FAILURE = "FETCH_PRODUCT_QUANTITY_FAILURE";

export const FETCH_TOTAL_PRODUCT_QUANTITY_REQUEST =
  "FETCH_TOTAL_PRODUCT_QUANTITY_REQUEST";
export const FETCH_TOTAL_PRODUCT_QUANTITY_SUCCESS =
  "FETCH_TOTAL_PRODUCT_QUANTITY_SUCCESS";
export const FETCH_TOTAL_PRODUCT_QUANTITY_FAILURE =
  "FETCH_TOTAL_PRODUCT_QUANTITY_FAILURE";


export const LIKE_PRODUCT_REQUEST = 'LIKE_PRODUCT_REQUEST';
export const LIKE_PRODUCT_SUCCESS = 'LIKE_PRODUCT_SUCCESS';
export const LIKE_PRODUCT_FAILURE = 'LIKE_PRODUCT_FAILURE';

export const DISLIKE_PRODUCT_REQUEST = 'DISLIKE_PRODUCT_REQUEST';
export const DISLIKE_PRODUCT_SUCCESS = 'DISLIKE_PRODUCT_SUCCESS';
export const DISLIKE_PRODUCT_FAILURE = 'DISLIKE_PRODUCT_FAILURE';
